# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalRegistrationFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=8, verbose_name='User Type')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Phone')),
                ('sch_org', models.CharField(blank=True, max_length=150)),
                ('organization_type', models.CharField(choices=[('corporate', 'Corporate'), ('school district', 'School District'), ('private school', 'Private School'), ('higher ed', 'Higher ED'), ('training', 'Training')], max_length=32, verbose_name='Organization Type')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
