# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-05 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalregistrationfields',
            name='user_type',
        )
    ]
